apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  name: argocd-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/Dodexq/kuber-cluster01'
    targetRevision: HEAD
    path: helm-chart/resume-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: resume
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---