apiVersion: v1
kind: ConfigMap
metadata:
  name: ip-masq-agent
  namespace: kube-system
data:
  config: |
    nonMasqueradeCIDRs:
      - 172.18.0.100/32
      - 10.96.0.1/12
      - 10.240.0.0/16
    masqLinkLocal: false
    resyncInterval: 30s