---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-volume
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-deployment
  labels:
    app: resume
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
        - name: resume
          image: dodexq/resume:v2.4
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
          livenessProbe:
            httpGet:
              path: /app/health/livenes
              port: 80
              scheme: "HTTP"
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /app/health/readnes
              port: 80
              scheme: "HTTP"
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
          - name: data
            mountPath: /var/www/html/persistent
      volumes:
      - name: data
        hostPath:
          path: /mnt/resume
          type: DirectoryOrCreate
---
kind: Service
apiVersion: v1
metadata:
  name: resume-svc
spec:
  selector:
    app: resume
  ports:
  - port: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-ingress
  annotations:
    #cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/server-snippet: |
      more_set_headers     "real_ip_recursive on";
      more_set_headers     "X-Real-IP $remote_addr";
      more_set_headers     "X-Forwarded-For $proxy_add_x_forwarded_for";
      more_set_headers     "Host $http_host";
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dodex.site
    secretName: app-tls
  rules:
  - host: dodex.site
    http:
      paths:
      - pathType: Prefix
        path: /
        backend: 
          service:
            name: resume-svc
            port:
              number: 80
---