---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resume-deployment
  labels:
    app: resume
spec:
  serviceName: "resume"
  replicas: 3
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
      - name: resume
        image: dodexq/resume:v2.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /app/health/livenes
            port: 80
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /app/health/readnes
            port: 80
            scheme: "HTTP"
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - name: data
          mountPath: "/var/www/html/persistent"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: resume-svc
spec:
  externalTrafficPolicy: Local
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: resume
  ports:
  - port: 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-ingress
  annotations:
    #Choice certificate
    #cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manager.io/cluster-issuer: letsencrypt-staging

    #Add real ip header
    nginx.ingress.kubernetes.io/configuration-snippet: |
       more_set_headers     "X-Real-IP $remote_addr";
       more_set_headers     "X-Forwarded-For $proxy_add_x_forwarded_for";
       more_set_headers     "Host $http_host";

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dodex.site
    secretName: app-tls
  rules:
  - host: dodex.site
    http:
      paths:
      - pathType: Prefix
        path: /
        backend: 
          service:
            name: resume-svc
            port:
              number: 80
---
