kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: ingress-nginx
data:
  use-proxy-protocol: "true"
  proxy-protocol-header-timeout: "5s"
  use-forwarded-headers: "true"
  add-headers: "X-Real-IP $remote_addr;"