stages:
  - build
build-job:
  stage: build
  tags: 
    - test-runner
  script:
    - echo "Compiling the code..."
    - python setup.py sdist
    - echo "Compile complete."
  artifacts: 
    paths:
      - dist/