apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-claim
spec:
  storageClassName: hostpath
  volumeName: example-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
