---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-volume
spec:
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: example-volume
    namespace: resume
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---